config/routes.rb
Rails.application.routes.draw do

root to: 'categories#index'

  resources :articles do
    resources :comments
    resources :versions
  end

  resources :categories
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post 'users' => 'users#create'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :creator, class_name: "User", foreign_key: :creator_id

  has_many :versions
  has_many :comments

  validates :creator, {presence: true}

  def latest_version
    self.versions.order("updated_at desc").where(published: true).first
  end

  def self.all_current_versions
    current_versions = []
    Article.all.each do |article|
      if article.latest_version
        current_versions << article.latest_version
      end
    end
    current_versions
  end

  def self.five_most_recent
    sorted_articles = Article.all_current_versions.sort_by! do |version|
      version.updated_at
    end
    return sorted_articles.reverse.slice(0,5)
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index

    @articles = Article.all
  end

  def show
    @current_version = Article.find(params[:id]).latest_version
    @article_comments = Article.find(params[:id]).comments
    doc = Nokogiri::HTML.fragment(@current_version.content)
    @sections = []
    doc.css('h3').each do |h3|
      @sections << h3.content
      h3["id"] = h3.content
    end

    @current_version.content = doc
  end

  def new
    if current_user
      @article = Article.new
      @version = @article.versions.new
    else
      @error = "WOOF WOOF WOOF"
    end
  end

  def create
    if current_user
      @article = Article.new(creator: current_user)

      @new_version = @article.versions.new(article_params)
      @new_version.editor = current_user

      if @article.save && @new_version.save
        if @new_version.published == true
          redirect_to article_path(@article)
        else
          redirect_to '/'
        end
      else
        # Add logic to accoutn validations
      end

    end
  end

  def destroy
    article = Article.find(params[:id])
    versions = Version.where(article_id: article.id ).destroy_all
    # flash.notice = "Article '#{article.title}' deleted!"
    article.destroy

    redirect_to '/'
  end

  # def edit
  #   @article = Article.find(params[:id]).latest_version
  # end

  # def update
  #   @article_object = Article.find(params[:id])
  #   @article = @article_object.latest_version
  #   @article.update(article_params)

  #   # flash.notice = "Article '#{@article.title}' Updated!"

  #   redirect_to article_path(@article_object)
  # end

  private
  def article_params
    params.require(:version).permit(:title, :content, :published, :all_sources)
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
  def featured_article
    Version.order(updated_at: :desc).first
  end
end

app/views/articles/_form.html.erb
<%= form_for @version, url: articles_path do |f| %>
  <ul>
  <% @version.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title, :class => 'subtitle form-title' %><br />
    <%= f.text_field :title, :class => 'ckeditor form-title' %>
  </p>
  <p>
    <%= f.label :content, :class => 'subtitle form-content' %><br />
    <%= f.text_area :content, :class => 'ckeditor form-content' %>
  </p>

  <!-- Add category & sources functionality -->
  <!-- NOTE: LN: Use the all_sources similar to the versions form -->

  <div class="published-button subtitle">
    <%= f.label "Publish?" %> <br />
    <%= f.check_box :published %> <br />
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<div class="form-container">
  <div class="title thicker"> Edit Article </div>
  <%= render partial: 'form' %>

</div>

app/views/articles/index.html.erb
<div class="articles-container see-through">
  <div class="title thicker" >All Articles</div>


  <table id="articles">
    <tr>
    <th><%= sort_link @articles, :title, "Title" %></th>
    <th><%= sort_link @articles, :updated_at, "Last Update Date" %></th>
    </tr>
    <%= @articles.class %>
    <% @articles.each do |article| %>
    <tr>
      <td> <a href="articles/<%= article.id %>"> <%= article.title %> </a></td>
      <td> <%= article.updated_at %></td>
    </tr>
    <% end %>
  </table>


  <%= link_to "Create a New Article", new_article_path, class: "new_article" %>
</div>

app/views/articles/new.html.erb
<div class="form-container">
  <div class="title thicker"> Create New Article!!!! </div>
    <% if @error %>
      <br>
      <br>
      <%= @error %>
      <img src="https://img.buzzfeed.com/buzzfeed-static/static/enhanced/webdr02/2012/12/15/17/anigif_enhanced-buzz-2771-1355609732-2.gif">
    <% else %>
      <%= render partial: 'form' %>
    <% end %>
</div>

app/views/articles/show.html.erb
<div class="article-container see-through center">


  <span class="page-title title thicker"> Article: <%= @current_version.title %> </span>
  <span class="article-editor info thicker"> Author: <%= @current_version.editor.username %> </span>


  <div class="article-categories border-bot">

  <% if current_user.clearance == "admin" || current_user.clearance == "moderator"%>
    <br><br>
    <span class="thicker"> Admin privileges: </span>
    <%= link_to "Delete", article_path(@current_version.article), method: :delete  %>
  <% end %>

    <span class="info thicker"> Categories: </span>

    <% @current_version.categories.each do |category| %>

      <span class="content thicker"> <%= link_to category.name, category_path(category) %> </span>

    <% end %>

  </div>

  <div class="section content">

    <h2> Table of Contents: </h2>
    <ul>

      <% @sections.each do |section| %>

        <li><%= link_to section, article_path(@current_version.article, anchor: section) %></li>

      <% end %>
    </ul>

  </div>

  <div class="article-content border-bot content"><%= @current_version.content.html_safe %></div>

  <div class="border-bot content">

    <h2 class="subtitle"> Comments: </h2>

      <% @article_comments.each_with_index do |comment, index| %>
        <div class="border-bot medium-width medium-pad">
          <span><%= (index + 1).to_s %>: <%=comment.content.html_safe %></span>
          <span>Commentor: <%=comment.user.username %></span><br>
        </div>
      <% end %>


    <% if current_user %>
      <p class="button subtitle">
        <%= link_to 'New Comment', new_article_comment_path(@current_version.article_id)%>
      </p>

    <% else %>
      <p>Log in to comment!</p>
    <% end %>

  </div>

  <div class="sources">
    <span class="subtitle thicker">Sources:</span><br><br>
    <% @current_version.sources.each do |source| %>

      <span class="content thicker each-source"> <%= link_to source.url, "http://#{source.url}"%> </span><br>

    <% end %>

  </div>

  <% if current_user %>
    <p class="edit-article info thicker"> <%= link_to 'Edit Article', new_article_version_path(@current_version.article_id)%></p>
    
  <% else %>
    <br>
    <br>
    <br>
    <p>Log in to edit!</p>
    <img src="https://media.giphy.com/media/UQDmnGZNm9Blu/giphy.gif">
  <% end %>

  <p>See all previous versions of this article <%= link_to 'here', article_versions_path(@current_version.article_id)%></p>

</div>