config/routes.rb
Rails.application.routes.draw do

root to: 'categories#index'

  resources :articles do
    resources :comments
    resources :versions
  end

  resources :categories
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post 'users' => 'users#create'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: :creator_id
  has_many :versions, foreign_key: :editor_id
  has_many :comments
  has_secure_password
  validates :username, :email, {presence: true}
  validates :username, {uniqueness: true}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  def new
  end

  def show
    @user = User.find(params[:id])
    if current_user.clearance == 'admin'
      puts '1'
      @user
    elsif current_user.id == @user.id
      puts '2'
      @user
    else
      puts '3'
      @user = current_user
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to "/"
    else
      redirect_to "signup"
    end
  end

  def update
    puts '-------------------------------------'
    puts params

    # The only way this ever gets updated is if the admin does it . If users can update their own profile then we need to change this update route completely
    @user = User.find(params[:ch_user_id])
    puts @user.id
    puts @user.clearance
    @user.update_attributes(clearance: params[:clearance])
    puts "ERRORS?: #{@user.errors.inspect}"
    puts @user.clearance
    puts @user.persisted?
    puts '-------------------------------------'
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper

  # Helper methods in Rails are only available to the view, unlike the Sinatra framework

  # Move #current_user to application_controller

  # Move #authorize to a Controller. Best practice? Probably to just move it to Users or Sessions Controller, but I'm moving it to App Controller too.
  ### NB: It shouldn't be here because its only purpose is to redirect -- put it in the controller, the views don't need access to that power!

  # Move #admin? to application_controller
end

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: "/users" do |f|  %>

  Username: <%= f.text_field :username %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  <%= f.submit "Submit" %>


<% end %>

app/views/users/show.html.erb
<div class="user-container see-through center">
  <span class="page-title title thicker"> <%= @user.username %>'s User Page </span><br><br>

  <div class="user-box subtitle thicker"> <%= @user.username %>'s Unpublished Work:

  <% if @user.versions %>
    <div class="cat-arts">
      <% @user.versions.where(published: false).each do |version| %>
        <%= link_to version.title, article_version_path(version.article_id, version), class: "each-version thicker info" %><br>

      <% end %>
    </div>
  <% end %>
  </div>




  <div class="user-box subtitle thicker"> <%= @user.username %>'s Published Work:

    <% if @user.versions %>
      <div class="cat-arts">
        <% @user.versions.where(published: true).each do |version| %>
          <%= link_to version.title, article_version_path(version.article_id, version), class: "each-version thicker info" %><br>
        <% end %>
      </div>
    <% end %>

  </div>
  <% if current_user.clearance == "admin" && @user.id == current_user.id%>
    <div class="user-box subtitle thicker">

        <h3>Users:</h3>
        <ul>
          <% User.all.each do |user| %>
            <% if user.clearance == "moderator" %>
              <li><%= link_to user.username, user_path(user) %></li>
              <%= link_to("Demote to editor", user_path(@user, clearance: "editor", ch_user_id: user.id), :method => :put) %><br><br>
            <% elsif user.clearance == "editor"%>
              <li><%= link_to user.username, user_path(user) %></li>
              <%= link_to("Promote to moderator", user_path(@user, clearance: "moderator", ch_user_id: user.id), :method => :put) %><br><br>
            <% end %>
          <% end %>
        </ul>

    </div>
  <% end %>
</div>