config/routes.rb
Rails.application.routes.draw do

root to: 'categories#index'

  resources :articles do
    resources :comments
    resources :versions
  end

  resources :categories
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post 'users' => 'users#create'

end

app/models/version.rb
class Version < ActiveRecord::Base
  belongs_to :article
  belongs_to :editor, class_name: "User", foreign_key: :editor_id

  has_many :categorizations
  has_many :categories, through: :categorizations
  has_many :sources

  validates :title, :content, :article, :editor, {presence: true}

  def all_sources=(new_sources)
    new_sources.split(' ').each do |source|
      sources.new(url: source)
    end
  end
  
  def self.search(search)
    where("title LIKE ?", "%#{search}%")
    where("content LIKE ?", "%#{search}%")
  end

end

app/controllers/versions_controller.rb
class VersionsController < ApplicationController

  def index
    @all_versions = Version.where(article_id: params[:article_id])
  end

  def show
    @version = Version.find(params[:id])
    doc = Nokogiri::HTML.fragment(@version.content)
    @sections = []
    doc.css('h3').each do |h3|
      @sections << h3.content
      h3["id"] = h3.content
    end

    @version.content = doc
  end

  def new
   if current_user
      @article = Article.find(params[:article_id])
      @version = Version.new
    else
      @error = "WOOF WOOF WOOF"
    end
  end

  def create
    if current_user
      @article = Article.find(params[:article_id])

      @version = @article.versions.new(version_params)
      @version.editor = current_user

      if @version.save
        redirect_to article_path(@article)
      else
        # Add logic to account validations
      end

    end
  end

  def destroy
    version = Version.find(params[:id])
    article = Article.find(params[:article_id])
    if article.versions.count == 1
      version.destroy
      article.destroy
      redirect_to '/'
    else
      version.destroy
      redirect_to action: "index"
    end
  end

  private
  def version_params
    params.require(:version).permit(:title, :content, :published, :categories, :all_sources)
  end

end

app/helpers/versions_helper.rb
module VersionsHelper

  def version_sources(article)
    source_urls = article.latest_version.sources.map { |source| source.url }
    source_urls.join(' ')
  end

end

app/views/versions/_form.html.erb
<%= form_for [article, version] do |f| %>
  <ul>
  <% version.errors.full_messages.each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
  <p>
    <%= f.label :title, :class => 'subtitle form-title' %><br />
    <%= f.text_field :title, :class => 'ckeditor form-title', :value => article.latest_version.title %>
  </p>
  <p>
    <%= f.label :content, :class => 'subtitle form-content' %><br />
    <%= f.text_area :content, :class => 'ckeditor form-content', :value => article.latest_version.content %>
  </p>

<!-- Would be nice to have the sources display better -->

  <p>
    <%= f.label :all_sources, :class => 'subtitle form-content' %>
    <%= f.text_field :all_sources, :class => 'ckeditor form-title', :value => version_sources(article) %>
  </p>

  <div class="published-button subtitle">
    <%= f.label "Publish?" %> <br />
    <%= f.check_box :published %> <br />
  </div>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/versions/index.html.erb
<div class="title thicker">
  All Versions:
</div>


<% if @all_versions %>
<div class="subtitle thicker">
  <% @all_versions.each do |version| %>
  <div class="thicker border-bot medium-width medium-pad" > 
    <span class="thicker subtitle"><%= version.title %> <%= link_to 'View here', article_version_path(version.article_id, version)%><br> As of: <%= version.created_at %> </span>
  </div> 
  <% end %>
</div>
<% end %>

<% if current_user.clearance == "admin" || current_user.clearance == "moderator"%>
  <span class="thicker"> Admin privileges: </span>
  <%= link_to "Delete", article_version_path(version.article_id, version), method: :delete  %>
<% end %>

app/views/versions/new.html.erb
<br>
<div class="form-container see-through">
  <div class="title thicker"> Edit Article </div>
  <%= render partial: 'form', locals: { article: @article, version: @version } %>

</div>

app/views/versions/show.html.erb
<div class="article-container see-through center">

  <h3>Version of <%= @version.article.latest_version.title %>: </h3>
  <p>As of: <%= @version.created_at %></p>

  <span class="article-title title thicker"> <%= @version.title %> </span>



  <span class="article-editor info thicker"> Author: <%= @version.editor.username %> </span>

  <% if current_user.clearance == "admin" || current_user.clearance == "moderator"%>
    <span class="thicker"> Admin privileges: </span>
    <%= link_to "Delete", article_version_path(@version.article_id, @version), method: :delete  %>
  <% end %>
  <br><br>

  <div class="article-categories border-bot">

    <span class="info thicker"> Categories: </span>

    <% @version.categories.each do |category| %>

      <span class="content thicker"> <%= link_to category.name, category_path(category) %> </span>

    <% end %>

  </div>

  <div class="section content">

    <h2> Table of Contents: </h2>
    <ul>

      <% @sections.each do |section| %>

        <li> <a href="http://localhost:3000/articles/<%=@version.article_id.to_s%>#<%= section %>"> <%= section %> </a></li>

      <% end %>
    </ul>

  </div>

  <div class="article-content border-bot content"><%= @version.content.html_safe %></div>

  <div class="sources">
    <span class="subtitle thicker">Sources:</span><br><br>
    <% @version.sources.each do |source| %>

      <span class="content thicker each-source"> <%= link_to source.url, "http://#{source.url}"%> </span><br>

    <% end %>

  </div>

  <img src="https://media.giphy.com/media/UQDmnGZNm9Blu/giphy.gif">


  <p>See all previous versions of this article <%= link_to 'here', article_versions_path(@version.article_id)%></p>

</div>