config/routes.rb
Rails.application.routes.draw do

root to: 'categories#index'

  resources :articles do
    resources :comments
    resources :versions
  end

  resources :categories
  resources :users

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post 'users' => 'users#create'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :categorizations
  has_many :versions, through: :categorizations

  validates :name, {presence: true}

  def self.current_articles(id)
    category_articles = []

    Article.all_current_versions.each do |version|
      version.categories.each do |category|
        if category == @category
          category_articles << version
        end
      end
    end

    category_articles
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
    @q = Version.ransack(params[:q])
    @articles = @q.result(distinct: true)
    @featured_articles = Article.five_most_recent
  end

  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @category_articles = []

    Article.all_current_versions.each do |version|
      version.categories.each do |category|
        if category == @category
          @category_articles << version
        end
      end
    end

    @category_articles
  end

  def create

  end



end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="categories-container see-through">

  <div class="search">

  </div>
  <div class="feature thicker subtitle">
    Featured Article:
    <% if @featured_articles %>

      <ul>
        <% @featured_articles.each do |featured_article| %>

          <!-- Date/time needs formatting -->

          <li><%= featured_article.title %> <%= link_to 'View here', article_path(featured_article.article_id)%> </li>

        <% end %>
      </ul>
    <% end %>
  </div>

  <div class="indextitle thicker title">All Categories</div>

  <div class="cats" id="thicker subtitle">
    <% @categories.each do |category| %>
      <div class="eachcat">
        <%= link_to category.name, category_path(category), class: "each-category thicker info" %>

      </div>
    <% end %>
  </div>


</div>

app/views/categories/show.html.erb
<div class="category-container see-through">
<!--   <span class="title thicker">Category: <%= @category.name %></span> -->

  <div class="title thicker category-articles">
    <%= @category.name %> Articles:
      <div class="cat-arts subtitle">

      <!-- We need to only grab the last one, push it into an array, then loop over and display the article -->

        <% @category_articles.each do |version| %>
            <%= link_to version.title, article_path(version.article_id) %>
        <% end %>

      </div>
  </div>
</div>


<!-- model tests -->
<!-- add features -->
<!-- feature tests -->
<!-- at very least test article creation -->